name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting --project=satzwuerfel
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
